### ISSUE TITLE
Setup Your Data Science Environment

### ISSUE THREAD

**Issue by danielrawlins21** [danielrawlins21/MentalHealth_DataAnalysis#2]
# Tasks
- [ ] **Task 1.** Choose Python as your programming language and install venv
- [ ] **Task 2.** Set up Jupyter notebook and explore the features of it
- [ ] **Task 3.** Configure and install requirements.txt with essential libraries:
> - Numpy 
> - Matplotlib
> - seaborn
> - Pandas
> - Scikit-learn
> - Pytorch
> - TensorFlow
> - Scipy
